---
layout: post
title: UnboundLocalError
---

Recently we had an ['UnboundLocalError' in mozci](https://pastebin.mozilla.org/8835719).A local variable was being referenced before assignment. Turns out we were only defining the variable in one branch of a 'if' statement. It was very [straightforward](https://github.com/armenzg/mozilla_ci_tools/pull/244/files) to fix. What bothered me was that this is the exact sort of error that would have been caught at compile time in other languages.

Is there a Python static analysis tool that would have caught this? I wrote a very simple module with the same bug and tried with different tools[^1]:

{% highlight python %}
"""This module bakes pizzas."""


def bake_pizza():
    """Bake a pizza."""
    number = int(raw_input())

    if number > 3:
        additional = 2
    else:
        number += 1
    print number + additional

if __name__ == '__main__':
    bake_pizza()
{% endhighlight %}

Neither pylint, pyflakes or pychecker were able to notify me about the possibility of an 'UnboundLocalError'.


[1]: It ended up being the only module I've ever written that scored 10.0/10 in pylint.
